name: Release binaries

permissions: read-all

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    permissions:
      contents: write
      # Packages write permission required to create a release
      packages: write
    runs-on:
      labels: ubuntu-22.04-8core
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3

      - name: "Run `bazel build`"
        run: |
          bazel build -c opt //tools:keymemrt-opt //tools:keymemrt-translate

      - name: Ensure binaries can run
        shell: bash
        run: |
            bazel-bin/tools/keymemrt-opt --help
            bazel-bin/tools/keymemrt-translate --help

      - name: GH Release
        uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0 #pin@v2.0.6
        with:
          files: |
            bazel-bin/tools/keymemrt-opt
            bazel-bin/tools/keymemrt-translate
